### ISSUE TITLE
Support "Flat Config" (ESLint 9)

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [polygonplanet/ESLint#30]
👋 Coming over from https://github.com/eslint/eslint/issues/18093: ESLint is migrating to a [new "flat config" format](https://eslint.org/docs/latest/use/configure/configuration-files-new) that will be the default in ESLint v9.

I tried this extension out in a repository with the new `eslint.config.js` (https://github.com/eslint/create-config) and got an error for a configuration not found:

```plaintext
/Users/josh/repos/create-config/node_modules/eslint/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:4000
            throw new ConfigurationNotFoundError(directoryPath);
                  ^

ConfigurationNotFoundError: No ESLint configuration found in /Users/josh/repos/create-config/lib/shared.
    at CascadingConfigArrayFactory._finalizeConfigArray (/Users/josh/repos/create-config/node_modules/eslint/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:4000:19)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/Users/josh/repos/create-config/node_modules/eslint/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3791:21)
    ...
```

I'm posting this issue here as a reference & cross-linking it to the table in https://github.com/eslint/eslint/issues/18093. If there's anything blocking the extension from supporting flat configs, please let us know - we'd be happy to try to help! 💜 

Additional resources:
* [Configuration Migration Guide](https://eslint.org/docs/latest/use/configure/migration-guide)
* _(edit)_ [Plugin Migration to Flat Config](https://eslint.org/docs/latest/extend/plugin-migration-flat-config)
* Blog posts on the new config system: [Part 1: Background](https://eslint.org/blog/2022/08/new-config-system-part-1/), [Part 2: Introduction to flat config](https://eslint.org/blog/2022/08/new-config-system-part-2/)

**Comment by adrian-gierakowski** [comment]
Interested in this as well
